"""Add Cascades

Revision ID: 1070bf5dfce5
Revises: 4da18ac1047e
Create Date: 2023-03-01 06:55:53.884700

"""
from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1070bf5dfce5'
down_revision = '4da18ac1047e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('asset_property_asset_id_fkey', 'asset_property', type_='foreignkey')
    op.create_foreign_key(None, 'asset_property', 'asset', ['asset_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('asset_property_name_asset_type_id_fkey', 'asset_property_name', type_='foreignkey')
    op.create_foreign_key(None, 'asset_property_name', 'asset_type', ['asset_type_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('hotspot_destination_pano_id_fkey', 'hotspot', type_='foreignkey')
    op.drop_constraint('hotspot_asset_id_fkey', 'hotspot', type_='foreignkey')
    op.drop_constraint('hotspot_pano_id_fkey', 'hotspot', type_='foreignkey')
    op.create_foreign_key(None, 'hotspot', 'pano', ['pano_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'hotspot', 'pano', ['destination_pano_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'hotspot', 'asset', ['asset_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('site_parent_site_id_fkey', 'site', type_='foreignkey')
    op.create_foreign_key(None, 'site', 'site', ['parent_site_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'site', type_='foreignkey')
    op.create_foreign_key('site_parent_site_id_fkey', 'site', 'site', ['parent_site_id'], ['id'])
    op.drop_constraint(None, 'hotspot', type_='foreignkey')
    op.drop_constraint(None, 'hotspot', type_='foreignkey')
    op.drop_constraint(None, 'hotspot', type_='foreignkey')
    op.create_foreign_key('hotspot_pano_id_fkey', 'hotspot', 'pano', ['pano_id'], ['id'])
    op.create_foreign_key('hotspot_asset_id_fkey', 'hotspot', 'asset', ['asset_id'], ['id'])
    op.create_foreign_key('hotspot_destination_pano_id_fkey', 'hotspot', 'pano', ['destination_pano_id'], ['id'])
    op.drop_constraint(None, 'asset_property_name', type_='foreignkey')
    op.create_foreign_key('asset_property_name_asset_type_id_fkey', 'asset_property_name', 'asset_type', ['asset_type_id'], ['id'])
    op.drop_constraint(None, 'asset_property', type_='foreignkey')
    op.create_foreign_key('asset_property_asset_id_fkey', 'asset_property', 'asset', ['asset_id'], ['id'])
    # ### end Alembic commands ###
