"""Initial Create

Revision ID: 5dd403e28449
Revises:
Create Date: 2023-02-27 05:25:34.159211

"""
from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5dd403e28449'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_type',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('original_icon_filename', sa.String(length=255), nullable=True),
    sa.Column('stored_icon_filename', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_table('site',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('coordinates', Geometry(geometry_type='POINT', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=False),
    sa.Column('parent_site_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_site_id'], ['site.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_index('idx_site_coordinates', 'site', ['coordinates'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_site_parent_site_id'), 'site', ['parent_site_id'], unique=False)
    op.create_table('asset_property_name',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('asset_type_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_type_id'], ['asset_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_property_name_asset_type_id'), 'asset_property_name', ['asset_type_id'], unique=False)
    op.create_table('survey',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('is_latest', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'is_latest')
    )
    op.create_index(op.f('ix_survey_site_id'), 'survey', ['site_id'], unique=False)
    op.create_table('floor',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('survey_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['survey_id'], ['survey.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_floor_survey_id'), 'floor', ['survey_id'], unique=False)
    op.create_geospatial_table('asset',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('coordinates', Geometry(geometry_type='POINT', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=False),
    sa.Column('asset_type_id', sa.Integer(), nullable=False),
    sa.Column('floor_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_type_id'], ['asset_type.id'], ),
    sa.ForeignKeyConstraint(['floor_id'], ['floor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_index('idx_asset_coordinates', 'asset', ['coordinates'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_asset_asset_type_id'), 'asset', ['asset_type_id'], unique=False)
    op.create_index(op.f('ix_asset_floor_id'), 'asset', ['floor_id'], unique=False)
    op.create_geospatial_table('floor_overlay',
    sa.Column('original_filename', sa.String(), nullable=False),
    sa.Column('stored_filename', sa.String(), nullable=False),
    sa.Column('extent', Geometry(geometry_type='POLYGON', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=False),
    sa.Column('floor_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['floor_id'], ['floor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_index('idx_floor_overlay_extent', 'floor_overlay', ['extent'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_floor_overlay_floor_id'), 'floor_overlay', ['floor_id'], unique=False)
    op.create_geospatial_table('photo',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('coordinates', Geometry(geometry_type='POINT', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=False),
    sa.Column('heading', sa.Float(), nullable=False),
    sa.Column('is_cubic_pano', sa.Boolean(), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('stored_filename', sa.String(length=255), nullable=True),
    sa.Column('custom_marker', sa.String(length=100), nullable=True),
    sa.Column('floor_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['floor_id'], ['floor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_index('idx_photo_coordinates', 'photo', ['coordinates'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_photo_floor_id'), 'photo', ['floor_id'], unique=False)
    op.create_table('asset_property',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_property_asset_id'), 'asset_property', ['asset_id'], unique=False)
    op.create_table('hotspot',
    sa.Column('source_photo_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('destination_photo_id', sa.Integer(), nullable=True),
    sa.Column('x_coord', sa.Float(), nullable=False),
    sa.Column('y_coord', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.ForeignKeyConstraint(['destination_photo_id'], ['photo.id'], ),
    sa.ForeignKeyConstraint(['source_photo_id'], ['photo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hotspot_asset_id'), 'hotspot', ['asset_id'], unique=False)
    op.create_index(op.f('ix_hotspot_destination_photo_id'), 'hotspot', ['destination_photo_id'], unique=False)
    op.create_index(op.f('ix_hotspot_source_photo_id'), 'hotspot', ['source_photo_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hotspot_source_photo_id'), table_name='hotspot')
    op.drop_index(op.f('ix_hotspot_destination_photo_id'), table_name='hotspot')
    op.drop_index(op.f('ix_hotspot_asset_id'), table_name='hotspot')
    op.drop_table('hotspot')
    op.drop_index(op.f('ix_asset_property_asset_id'), table_name='asset_property')
    op.drop_table('asset_property')
    op.drop_index(op.f('ix_photo_floor_id'), table_name='photo')
    op.drop_geospatial_index('idx_photo_coordinates', table_name='photo', postgresql_using='gist', column_name='coordinates')
    op.drop_geospatial_table('photo')
    op.drop_index(op.f('ix_floor_overlay_floor_id'), table_name='floor_overlay')
    op.drop_geospatial_index('idx_floor_overlay_extent', table_name='floor_overlay', postgresql_using='gist', column_name='extent')
    op.drop_geospatial_table('floor_overlay')
    op.drop_index(op.f('ix_asset_floor_id'), table_name='asset')
    op.drop_index(op.f('ix_asset_asset_type_id'), table_name='asset')
    op.drop_geospatial_index('idx_asset_coordinates', table_name='asset', postgresql_using='gist', column_name='coordinates')
    op.drop_geospatial_table('asset')
    op.drop_index(op.f('ix_floor_survey_id'), table_name='floor')
    op.drop_table('floor')
    op.drop_index(op.f('ix_survey_site_id'), table_name='survey')
    op.drop_table('survey')
    op.drop_index(op.f('ix_asset_property_name_asset_type_id'), table_name='asset_property_name')
    op.drop_table('asset_property_name')
    op.drop_index(op.f('ix_site_parent_site_id'), table_name='site')
    op.drop_geospatial_index('idx_site_coordinates', table_name='site', postgresql_using='gist', column_name='coordinates')
    op.drop_geospatial_table('site')
    op.drop_table('asset_type')
    # ### end Alembic commands ###
