"""Add Overlay Name

Revision ID: a43f82969c93
Revises: 1070bf5dfce5
Create Date: 2023-03-03 06:51:58.419399

"""
from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a43f82969c93'
down_revision = '1070bf5dfce5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('overlay', sa.Column('name', sa.String(length=100), nullable=True))
    op.execute("UPDATE overlay set name = ''")
    op.alter_column('overlay', 'name', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('overlay', 'name')
    # ### end Alembic commands ###
